services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: itunes_podcasts
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@postgres:5432/itunes_podcasts
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
